" Both required for Vundle 
set nocompatible
filetype off

" Set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Plugins
Plugin 'yuezk/vim-js'
Plugin 'pangloss/vim-javascript'
Plugin 'leafgarland/typescript-vim'
Plugin 'maxmellon/vim-jsx-pretty'
Plugin 'neoclide/coc.nvim', {'branch': 'release'}
Plugin 'styled-components/vim-styled-components'
Plugin 'arcticicestudio/nord-vim'
Plugin 'dracula/vim', {'name': 'dracula'}

" All Plugins must be above this line
call vundle#end()
filetype plugin indent on

" Set color scheme
colorscheme dracula

" Search down into subfolders
" Provide tab-completion for all file-related tasks
set path+=**

" Ignore node_modules for finding
set wildignore+=**/node_modules/** 

" Enable nice menu for tab completion file names
set wildmenu

" Move up and down by visible lines if current line is wrapped
nmap j gj
nmap k gk

" Configure indentation
set tabstop=2
set shiftwidth=2
set expandtab

" Enable syntax highlighting
syntax enable

" Keep at least 4 lines below cursor
set scrolloff=4

" Set relative line numbering with absolute number for current line
set number relativenumber

" Rapid editing of Vimrc
nmap <leader>vr :sp $MYVIMRC<cr>
nmap <leader>so :source $MYVIMRC<cr>

" CoC configuration
let g:coc_global_extensions = ['coc-react-refactor', 'coc-prettier', 'coc-eslint', 'coc-tsserver', 'coc-styled-components']

" CoC actions
nmap <leader>a <Plug>(coc-codeaction)
nmap <leader>rn <Plug>(coc-rename)

" Prettier command
command! -nargs=0 Prettier :call CocAction('runCommand', 'prettier.formatFile')
